{
  "contest": 290,
  "handle": "0xDemon",
  "risk": "2",
  "title": "External call in loop can lead to Denial of Service (DoS)",
  "issueId": 300,
  "issueUrl": "https://github.com/code-423n4/2023-09-venus-findings/issues/300"
}